rem ------------------------------------------------------------------
rem @echo off
set IthRoot="%~dp0"
mkdir "32feet.NET installer"
mkdir "32feet.NET installer Symbols"
copy %IthRoot%"\Readme\Readme.rtf"  "32feet.NET installer\"
copy %IthRoot%"\Readme\32feet.NET -- User Guide.doc"  "32feet.NET installer\"
copy %IthRoot%"\Widcomm\32feet and Widcomm-Broadcom.doc"  "32feet.NET installer\"
rem Hidden file-- copy %IthRoot%"\Installer\favicon.ico"  "32feet.NET installer\"
copy %IthRoot%"\Installer\InstallBanner.jpg"  "32feet.NET installer\"
@echo off
rem The ones below should work!
rem ------------------------------------------------------------------
echo * Assemblies
mkdir "32feet.NET installer\Assemblies\XP2"
copy %IthRoot%"\InTheHand.Net.Personal\bin\Release\InTheHand.Net.Personal.dll"  "32feet.NET installer\Assemblies\XP2\"
copy %IthRoot%"\InTheHand.Net.Personal\bin\Release\InTheHand.Net.Personal.XML"  "32feet.NET installer\Assemblies\XP2\"
copy %IthRoot%"\InTheHand.Net.Personal\bin\Release\InTheHand.Net.Personal.dll.config"  "32feet.NET installer\Assemblies\XP2\app.config"
mkdir "32feet.NET installer\Assemblies\CE2"
copy %IthRoot%"\InTheHand.Net.Personal.CF2\bin\Release\InTheHand.Net.Personal.dll"  "32feet.NET installer\Assemblies\CE2\"
copy %IthRoot%"\InTheHand.Net.Personal.CF2\bin\Release\InTheHand.Net.Personal.XML"  "32feet.NET installer\Assemblies\CE2\"
rem Symbols
mkdir "32feet.NET installer Symbols\Assemblies\XP2"
mkdir "32feet.NET installer Symbols\Assemblies\CE2"
copy %IthRoot%"\InTheHand.Net.Personal\bin\Release\InTheHand.Net.Personal.pdb"  "32feet.NET installer Symbols\Assemblies\XP2\"
copy %IthRoot%"\InTheHand.Net.Personal.CF2\bin\Release\InTheHand.Net.Personal.pdb"  "32feet.NET installer Symbols\Assemblies\CE2\"
rem ------------------------------------------------------------------
echo * Widcomm native
rem Win32 WidcommSdk5 -- multi-stack
mkdir "32feet.NET installer\Assemblies\XP2\Widcomm x86"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\release\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\XP2\Widcomm x86\"
copy %IthRoot%"\release\Test32FeetWidcommWin32.exe"  "32feet.NET installer\Assemblies\XP2\Widcomm x86\"
mkdir "32feet.NET installer\Assemblies\XP2\Widcomm x64"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\x64\release\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\XP2\Widcomm x64\"
copy %IthRoot%"\x64\release\Test32FeetWidcommWin32.exe"  "32feet.NET installer\Assemblies\XP2\Widcomm x64\"
rem Win32 WidcommSdk6
mkdir "32feet.NET installer\Assemblies\XP2\Widcomm x86 SDK6"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\release WcSdk6\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\XP2\Widcomm x86 SDK6\"
mkdir "32feet.NET installer\Assemblies\XP2\Widcomm x64 SDK6"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\x64\release WcSdk6\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\XP2\Widcomm x64 SDK6\"
rem Win32 WidcommSdk6b
mkdir "32feet.NET installer\Assemblies\XP2\Widcomm x86 SDK6b"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\release BtSdk6\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\XP2\Widcomm x86 SDK6b\"
mkdir "32feet.NET installer\Assemblies\XP2\Widcomm x64 SDK6b"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\x64\release BtSdk6\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\XP2\Widcomm x64 SDK6b\"
rem WM/PPC
mkdir "32feet.NET installer\Assemblies\CE2\Widcomm WM5"
copy %IthRoot%"\Widcomm\32feetWidcommWM\Windows Mobile 5.0 Smartphone SDK (ARMV4I)\Release\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\CE2\Widcomm WM5\"
mkdir "32feet.NET installer\Assemblies\CE2\Widcomm PPC2003"
copy %IthRoot%"\Widcomm\32feetWidcommWM\Pocket PC 2003 (ARMV4)\Release\32feetWidcomm.dll"  "32feet.NET installer\Assemblies\CE2\Widcomm PPC2003\"
rem Symbols
rem x86
mkdir "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x86"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\release\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x86\"
mkdir "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x86 SDK6"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\release WcSdk6\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x86 SDK6\"
mkdir "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x86 SDK6b"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\release BtSdk6\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x86 SDK6b\"
rem x64
mkdir "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x64"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\x64\release\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x64\"
mkdir "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x64 SDK6"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\x64\release WcSdk6\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x64 SDK6\"
mkdir "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x64 SDK6b"
copy %IthRoot%"\Widcomm\32feetWidcommWin32Vs5\x64\release BtSdk6\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\XP2\Widcomm x64 SDK6b\"
rem WM/PPC
mkdir "32feet.NET installer Symbols\Assemblies\CE2\Widcomm WM5"
copy %IthRoot%"\Widcomm\32feetWidcommWM\Windows Mobile 5.0 Smartphone SDK (ARMV4I)\Release\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\CE2\Widcomm WM5\"
mkdir "32feet.NET installer Symbols\Assemblies\CE2\Widcomm PPC2003"
copy %IthRoot%"\Widcomm\32feetWidcommWM\Pocket PC 2003 (ARMV4)\Release\32feetWidcomm.pdb"  "32feet.NET installer Symbols\Assemblies\CE2\Widcomm PPC2003\"
rem ------------------------------------------------------------------
echo * Help
mkdir "32feet.NET installer\Help"
copy %IthRoot%"\doc\ThirtyTwoFeet.chm"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\H2Reg.exe"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\h2reg.ini"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\H2Reg_Log.txt"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet.chm"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet.hxc"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet.HxS"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet.HxT"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet_a.hxk"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet_b.hxk"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet_f.hxk"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet_k.hxk"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet_n.hxk"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet_NamedURLIndex.hxk"  "32feet.NET installer\Help\"
rem  copy %IthRoot%"\Help\ThirtyTwoFeet_s.hxk"  "32feet.NET installer\Help\"
rem ------------------------------------------------------------------
echo * Samples
mkdir "32feet.NET installer\Samples"
copy %IthRoot%"\Installer\32feet.NET Samples -- desktop only.sln"  "32feet.NET installer\Samples\"
copy %IthRoot%"\Installer\32feet.NET Samples.sln"  "32feet.NET installer\Samples\"

mkdir "32feet.NET installer\Samples\Common"
copy %IthRoot%"\Samples\Common\32feet.ico"  "32feet.NET installer\Samples\Common\"
copy %IthRoot%"\Samples\Common\32feet.128.png"  "32feet.NET installer\Samples\Common\"

mkdir "32feet.NET installer\Samples\BluetoothChat\Desktop"
copy %IthRoot%"\Samples\BluetoothChat\Desktop\32feet.ico"  "32feet.NET installer\Samples\BluetoothChat\Desktop\"
copy %IthRoot%"\Samples\BluetoothChat\Desktop\AssemblyInfo.vb"  "32feet.NET installer\Samples\BluetoothChat\Desktop\"
copy %IthRoot%"\Samples\BluetoothChat\Desktop\BluetoothChatDesktop.vbproj"  "32feet.NET installer\Samples\BluetoothChat\Desktop\"
copy %IthRoot%"\Installer\Installer_Desktop_4deep.XXproj.user"  "32feet.NET installer\Samples\BluetoothChat\Desktop\BluetoothChatDesktop.vbproj.user"
copy %IthRoot%"\Samples\BluetoothChat\Desktop\ChatForm.resx"  "32feet.NET installer\Samples\BluetoothChat\Desktop\"
copy %IthRoot%"\Samples\BluetoothChat\Desktop\ChatForm.vb"  "32feet.NET installer\Samples\BluetoothChat\Desktop\"
mkdir "32feet.NET installer\Samples\BluetoothChat\PocketPC"
copy %IthRoot%"\Samples\BluetoothChat\Pocket PC\32feet.ico"  "32feet.NET installer\Samples\BluetoothChat\PocketPC\"
copy %IthRoot%"\Samples\BluetoothChat\Pocket PC\AssemblyInfo.vb"  "32feet.NET installer\Samples\BluetoothChat\PocketPC\"
copy %IthRoot%"\Samples\BluetoothChat\Pocket PC\BluetoothChatPPC.vbproj"  "32feet.NET installer\Samples\BluetoothChat\PocketPC\"
copy %IthRoot%"\Installer\Installer_netcf_4deep.XXproj.user"  "32feet.NET installer\Samples\BluetoothChat\PocketPC\BluetoothChatPPC.vbproj.user"
copy %IthRoot%"\Samples\BluetoothChat\Pocket PC\ChatForm.resx"  "32feet.NET installer\Samples\BluetoothChat\PocketPC\"
copy %IthRoot%"\Samples\BluetoothChat\Pocket PC\ChatForm.vb"  "32feet.NET installer\Samples\BluetoothChat\PocketPC\"
mkdir "32feet.NET installer\Samples\BluetoothChat\Smartphone"
copy %IthRoot%"\Samples\BluetoothChat\Smartphone\32feet.ico"  "32feet.NET installer\Samples\BluetoothChat\Smartphone\"
copy %IthRoot%"\Samples\BluetoothChat\Smartphone\AssemblyInfo.vb"  "32feet.NET installer\Samples\BluetoothChat\Smartphone\"
copy %IthRoot%"\Samples\BluetoothChat\Smartphone\BluetoothChatSmartphone.vbproj"  "32feet.NET installer\Samples\BluetoothChat\Smartphone\"
copy %IthRoot%"\Installer\Installer_NETCF_4deep.XXproj.user"  "32feet.NET installer\Samples\BluetoothChat\Smartphone\BluetoothChatSmartphone.vbproj.user"
copy %IthRoot%"\Samples\BluetoothChat\Smartphone\ChatForm.resx"  "32feet.NET installer\Samples\BluetoothChat\Smartphone\"
copy %IthRoot%"\Samples\BluetoothChat\Smartphone\ChatForm.vb"  "32feet.NET installer\Samples\BluetoothChat\Smartphone\"
mkdir "32feet.NET installer\Samples\BluetoothRemote"
REM ======== copy %IthRoot%"\Samples\BluetoothRemote\32feetback.jpg"  "32feet.NET installer\Samples\BluetoothRemote\"
copy %IthRoot%"\Samples\BluetoothRemote\AssemblyInfo.cs"  "32feet.NET installer\Samples\BluetoothRemote\"
copy %IthRoot%"\Samples\BluetoothRemote\BluetoothRemote.csproj"  "32feet.NET installer\Samples\BluetoothRemote\"
copy %IthRoot%"\Installer\Installer_NETCF_3deep.XXproj.user"  "32feet.NET installer\Samples\BluetoothRemote\BluetoothRemote.csproj.user"
copy %IthRoot%"\Samples\BluetoothRemote\RemoteControlForm.cs"  "32feet.NET installer\Samples\BluetoothRemote\"
copy %IthRoot%"\Samples\BluetoothRemote\RemoteControlForm.resx"  "32feet.NET installer\Samples\BluetoothRemote\"
mkdir "32feet.NET installer\Samples\BluetoothRemote\DesktopListener"
copy %IthRoot%"\Samples\BluetoothRemote\DesktopListener\AssemblyInfo.cs"  "32feet.NET installer\Samples\BluetoothRemote\DesktopListener\"
copy %IthRoot%"\Samples\BluetoothRemote\DesktopListener\BluetoothRemote.ico"  "32feet.NET installer\Samples\BluetoothRemote\DesktopListener\"
copy %IthRoot%"\Samples\BluetoothRemote\DesktopListener\BluetoothRemoteListener.csproj"  "32feet.NET installer\Samples\BluetoothRemote\DesktopListener\"
copy %IthRoot%"\Installer\Installer_Desktop_4deep.XXproj.user"  "32feet.NET installer\Samples\BluetoothRemote\DesktopListener\BluetoothRemoteListener.csproj.user"
copy %IthRoot%"\Samples\BluetoothRemote\DesktopListener\ListenerForm.cs"  "32feet.NET installer\Samples\BluetoothRemote\DesktopListener\"
copy %IthRoot%"\Samples\BluetoothRemote\DesktopListener\ListenerForm.resx"  "32feet.NET installer\Samples\BluetoothRemote\DesktopListener\"
mkdir "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\Data.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\Form1.Designer.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\Form1.resx"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\Form1.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\FormSelectServiceClasses.Designer.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\FormSelectServiceClasses.resx"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\FormSelectServiceClasses.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\SdpBrowserDesktop.vbproj"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\"
copy %IthRoot%"\Installer\Installer_Desktop_4deep.XXproj.user"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\SdpBrowserDesktop.vbproj.user"
mkdir "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\Application.Designer.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\Application.myapp"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\AssemblyInfo.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\Resources.Designer.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\Resources.resx"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\Settings.Designer.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\Settings.settings"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\"
REM mkdir "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\DataSources"
REM copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\DataSources\InTheHand.Net.Sockets.BluetoothDeviceInfo.datasource"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDesktop\My Project\DataSources\"
mkdir "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\SdpBrowserDevice.vbproj"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\"
copy %IthRoot%"\Installer\Installer_NETCF_4deep.XXproj.user"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\SdpBrowserDevice.vbproj.user"
mkdir "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\My Project"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\My Project\AssemblyInfo.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\My Project\Resources.Designer.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\My Project\Resources.resx"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\My Project\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\Clipboard.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\Form1.resx"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\Form1.Designer.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\"
copy %IthRoot%"\Samples\BluetoothSDP\SdpBrowserDevice\Form1.vb"  "32feet.NET installer\Samples\BluetoothSDP\SdpBrowserDevice\"
mkdir "32feet.NET installer\Samples\IrDA\IrDAServiceClient"
REM ==================== copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\32feet.ico"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Data.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Form1.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Form1.Designer.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Form1.resx"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\IrDAServiceClient.csproj"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\"
copy %IthRoot%"\Installer\Installer_Desktop_3deep.XXproj.user"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\IrDAServiceClient.csproj.user"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Program.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\"
mkdir "32feet.NET installer\Samples\IrDA\IrDAServiceClient\Properties"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Properties\AssemblyInfo.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\Properties\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Properties\Resources.Designer.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\Properties\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Properties\Resources.resx"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\Properties\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Properties\Settings.Designer.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\Properties\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClient\Properties\Settings.settings"  "32feet.NET installer\Samples\IrDA\IrDAServiceClient\Properties\"
mkdir "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2"
REM ======== copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\32feet.ico"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\Form1.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\Form1.Designer.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\Form1.resx"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\IrDAServiceClientCF2.csproj"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\"
copy %IthRoot%"\Installer\Installer_NETCF_3deep.XXproj.user"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\IrDAServiceClientCF2.csproj.user"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\Program.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\"
mkdir "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\Properties"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\Properties\AssemblyInfo.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\Properties\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\Properties\Resources.Designer.cs"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\Properties\"
copy %IthRoot%"\Samples\IrDA\IrDAServiceClientCF2\Properties\Resources.resx"  "32feet.NET installer\Samples\IrDA\IrDAServiceClientCF2\Properties\"
mkdir "32feet.NET installer\Samples\ObjectPush\DesktopObexListener"
REM ======== copy %IthRoot%"\Samples\ObjectPush\DesktopListener\32feet.ico"  "32feet.NET installer\Samples\ObjectPush\DesktopObexListener\"
copy %IthRoot%"\Samples\ObjectPush\DesktopListener\AssemblyInfo.cs"  "32feet.NET installer\Samples\ObjectPush\DesktopObexListener\"
copy %IthRoot%"\Samples\ObjectPush\DesktopListener\DesktopListener.csproj"  "32feet.NET installer\Samples\ObjectPush\DesktopObexListener\"
copy %IthRoot%"\Installer\Installer_Desktop_3deep.XXproj.user"  "32feet.NET installer\Samples\ObjectPush\DesktopObexListener\DesktopListener.csproj.user"
copy %IthRoot%"\Samples\ObjectPush\DesktopListener\ListenerForm.cs"  "32feet.NET installer\Samples\ObjectPush\DesktopObexListener\"
copy %IthRoot%"\Samples\ObjectPush\DesktopListener\ListenerForm.resx"  "32feet.NET installer\Samples\ObjectPush\DesktopObexListener\"
mkdir "32feet.NET installer\Samples\ObjectPush\DesktopPushVB"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\DesktopPushVB.vbproj"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\"
copy %IthRoot%"\Installer\Installer_Desktop_3deep.XXproj.user"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\DesktopPushVB.vbproj.user"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\Form1.vb"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\Form1.Designer.vb"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\Form1.resx"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\"
mkdir "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\My Project\Application.Designer.vb"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\My Project\Application.myapp"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\My Project\AssemblyInfo.vb"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\My Project\Resources.Designer.vb"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\My Project\Resources.resx"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\My Project\Settings.Designer.vb"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project\"
copy %IthRoot%"\Samples\ObjectPush\DesktopPushVB\My Project\Settings.settings"  "32feet.NET installer\Samples\ObjectPush\DesktopPushVB\My Project\"
mkdir "32feet.NET installer\Samples\ObjectPush\DeviceObexListener"
copy %IthRoot%"\Samples\ObjectPush\DeviceListener\DeviceListener.csproj"  "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\"
copy %IthRoot%"\Installer\Installer_NETCF_3deep.XXproj.user"  "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\DeviceListener.csproj.user"
copy %IthRoot%"\Samples\ObjectPush\DeviceListener\Form1.cs"  "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\"
copy %IthRoot%"\Samples\ObjectPush\DeviceListener\Form1.resx"  "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\"
mkdir "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\Properties"
copy %IthRoot%"\Samples\ObjectPush\DeviceListener\Properties\AssemblyInfo.cs"  "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\Properties\"
copy %IthRoot%"\Samples\ObjectPush\DeviceListener\Properties\Resources.Designer.cs"  "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\Properties\"
copy %IthRoot%"\Samples\ObjectPush\DeviceListener\Properties\Resources.resx"  "32feet.NET installer\Samples\ObjectPush\DeviceObexListener\Properties\"
mkdir "32feet.NET installer\Samples\ObjectPush\ObexPushVB"
REM ======== copy %IthRoot%"\Samples\ObjectPush\ObexPushVB\32feetback.jpg"  "32feet.NET installer\Samples\ObjectPush\ObexPushVB\"
copy %IthRoot%"\Samples\ObjectPush\ObexPushVB\AssemblyInfo.vb"  "32feet.NET installer\Samples\ObjectPush\ObexPushVB\"
copy %IthRoot%"\Samples\ObjectPush\ObexPushVB\Form1.resx"  "32feet.NET installer\Samples\ObjectPush\ObexPushVB\"
copy %IthRoot%"\Samples\ObjectPush\ObexPushVB\Form1.vb"  "32feet.NET installer\Samples\ObjectPush\ObexPushVB\"
copy %IthRoot%"\Samples\ObjectPush\ObexPushVB\ObexPushVB.vbproj"  "32feet.NET installer\Samples\ObjectPush\ObexPushVB\"
copy %IthRoot%"\Installer\Installer_NETCF_3deep.XXproj.user"  "32feet.NET installer\Samples\ObjectPush\ObexPushVB\ObexPushVB.vbproj.user"
mkdir "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication"
REM ======== copy %IthRoot%"\Samples\ObjectPush\ObjectPushApplication\32feet.ico"  "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication\"
REM ======== copy %IthRoot%"\Samples\ObjectPush\ObjectPushApplication\32feetback.jpg"  "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication\"
copy %IthRoot%"\Samples\ObjectPush\ObjectPushApplication\AssemblyInfo.cs"  "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication\"
copy %IthRoot%"\Samples\ObjectPush\ObjectPushApplication\ObjectPushApplication.csproj"  "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication\"
copy %IthRoot%"\Installer\Installer_NETCF_3deep.XXproj.user"  "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication\ObjectPushApplication.csproj.user"
copy %IthRoot%"\Samples\ObjectPush\ObjectPushApplication\ObjectPushForm.cs"  "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication\"
copy %IthRoot%"\Samples\ObjectPush\ObjectPushApplication\ObjectPushForm.resx"  "32feet.NET installer\Samples\ObjectPush\ObjectPushApplication\"
rem ------------------------------------------------------------------
echo on
setlocal
set MSBUILD=C:\WINDOWS\Microsoft.NET\Framework\v3.5\MSBuild.exe
pause Run Samples Build (desktop only)
%MSBUILD% "32feet.NET installer\Samples\32feet.NET Samples -- desktop only.sln"
pause Run Samples Build (all)
%MSBUILD% "32feet.NET installer\Samples\32feet.NET Samples.sln"
rem ------------------------------------------------------------------
rem EOF
