//-----------------------------------------------------------------------
// <copyright file="BluetoothCompanyId.cs" company="In The Hand Ltd">
//   Copyright (c) 2017 In The Hand Ltd, All rights reserved.
//   This source code is licensed under the MIT License - see License.txt
// </copyright>
//-----------------------------------------------------------------------

namespace InTheHand.Devices.Bluetooth
{
    /// <summary>
    /// Company identifiers are unique numbers assigned by the Bluetooth SIG to member companies requesting one.
    /// </summary>
    /// <remarks>The full list is maintained on the <a href="https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers">Bluetooth SIG website</a>.</remarks>
    public enum BluetoothCompanyId : ushort
    {
        Ericsson = 0,
        Nokia = 1,
        Intel = 2,
        IBM = 3,
        Toshiba = 4,
        ThreeCom=5,
        Microsoft=6,
        Lucent =7,
        Motorola=8,
        Infineon=9,
        CambridgeSiliconRadio=10,
        SiliconWave=11,
        Digianswer=12,
        TexasInstruments=13,
        ParthusTechnologies=14,
        Broadcom=15,
        Mitel=16,
        Widcomm=17,
        Zeevo=18,
        Atmel=19,
        MitsubishiElectric=20,
        RTXTelecom=21,
        KCTechnology=22,
        Newlogic=23,
        Transilica=24,
        RohdeAndSchwarz=25,
        TTPCom=26,
        SigniaTechnologies=27,
        Conexant=28,
        Qualcomm=29,
        Inventel=30,
        AVMBerlin=31,
        BandSpeed=32,
        Mansella=33,
        NEC=34,
        WavePlus=35,
        Alcatel=36,
        NXPSemiconductors=37,
        CTechnologies=38,
        OpenInterface=39,
        RFMicroDevices=40,
        Hitachi=41,
        Symbol=42,
        Tenovis=43,
        Macronix=44,
        GCTSemiconductor=45,
        NorwoodSystems=46,
        MewTelTechnologies=47,
        STMicroelectronics=48,
        Synopsys=49,
        RedM=50,
        Commil=51,
        ComputerAccessTechnologyCorporation=52,
        Eclipse=53,
        RenesasElectronics=54,
        Mobilian=55,
        Terax=56,
        IntegratedSystemSolution=57,
        Matsushita=58,
        Gennum=59,
        Blackberry=60,
        IPextreme=61,
        SystemsAndChips=62,
        BluetoothSIG=63,
        SeikoEpson=64,
        IntegratedSiliconSolutionTaiwan=65,
        ConwiseTechnology=66,
        Parrot=67,
        SocketMobile=68,
        Atheros=69,
        MediaTek=70,
        Bluegiga=71,
        Marvell=72,
        ThreeDSP=73,
        AccelSemiconductor=74,
        ContinentalAutomotiveSystems=75,
        Apple=76,
        Staccato=77,
        Avago=78,
        APT=79,
        SiRFTechnology=80,
        Tzero=81,
        JAndM=82,
        Free2move=83,
        ThreeDiJoy=84,
        Plantronics=85,
        SonyEricsson=86,
        Harman=87,
        Vizio=88,
        NordicSemiconductor=89,
        EMMicroelectronic=90,
        RalinkTechnology=91,
        Belkin=92,
        Realtek=93,
        StonestreetOne=94,
        Wicentric=95,
        RivieraWaves=96,
        RDAMicroelectronics=97,
        GibsonGuitars=98,
        MiCommand=99,
        BandXI=100,
        HewlettPackard=101,
        NineSolutions=102,
        GNNetcom=103,
        GeneralMotors=104,
        AandDEngineering=105,
        MindTree=106,
        PolarElectro=107,
        BeautifulEnterprise=108,
        BriarTek=109,
        SummitDataCommunications=110,
        SoundID=111,
        Monster=112,
        ConnectBlue=113,
        ShangHaiSuperSmartElectronics=114,
        GroupSense=115,
        Zomm=116,
        Samsung=117,
        CreativeTechnology=118,
        LairdTechnologies=119,
        Nike=120,
        Lesswire=121,
        MStarSemiconductor=122,
        HanlynnTechnologies=123,
        AandRCambridge=124,
        SeersTechnology=125,
        SportsTrackingTechnology=126,
        AutonetMobile=127,
        DeLormePublishing=128,
        WuXiVimicro=129,
        Sennheiser=130,
        TimeKeepingSystems=131,
        LudusHelsinki=132,
        BlueRadios=133,
        Equinux=134,
        Garmin=135,
        Ecotest=136,
        GNReSound=137,
        Jawbone=138,
        TopconPositioningSystems=139,
        Gimbal=140,
        Zscan=141,
        Quintic=142,
        TelitWirelessSolutions=143,
        FunaiElectric=144,
        AdvancedPanmobilSystems=145,
        ThinkOptics=146,
        UniversalElectronics=147,
        AirohaTechnology=148,
        NECLighting=149,
        ODMTechnology=150,
    }
}